/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const AnalysisRecord = IDL.Record({
  'id' : IDL.Nat,
  'generatedSQL' : IDL.Text,
  'analysisName' : IDL.Text,
  'createdAt' : Time,
  'user' : IDL.Principal,
  'grade' : IDL.Text,
  'tableName' : IDL.Text,
  'healthScore' : IDL.Nat,
  'violationsSummary' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteAnalysis' : IDL.Func([IDL.Nat], [], []),
  'getAllAnalyses' : IDL.Func([], [IDL.Vec(AnalysisRecord)], ['query']),
  'getAnalysisById' : IDL.Func([IDL.Nat], [IDL.Opt(AnalysisRecord)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyAnalyses' : IDL.Func([], [IDL.Vec(AnalysisRecord)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveAnalysis' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const AnalysisRecord = IDL.Record({
    'id' : IDL.Nat,
    'generatedSQL' : IDL.Text,
    'analysisName' : IDL.Text,
    'createdAt' : Time,
    'user' : IDL.Principal,
    'grade' : IDL.Text,
    'tableName' : IDL.Text,
    'healthScore' : IDL.Nat,
    'violationsSummary' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteAnalysis' : IDL.Func([IDL.Nat], [], []),
    'getAllAnalyses' : IDL.Func([], [IDL.Vec(AnalysisRecord)], ['query']),
    'getAnalysisById' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(AnalysisRecord)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyAnalyses' : IDL.Func([], [IDL.Vec(AnalysisRecord)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveAnalysis' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };